### ISSUE TITLE
Errore Deserializzazione Coordinate

### ISSUE THREAD

**Issue by brux88** [Samurai016/Comuni-ITA-legacy#2]
cioa, ho notato che alcune coordinate sono tra apici e altri no quindi quando faccio il deserialize va in errore:

esempio:

{"nome":"Zafferana Etnea","codice":"087055","regione":"sicilia","provincia":"catania","sigla":"CT","codiceCatastale":"M139","cap":"95019","coordinate":**{"lat":37.690411,"lng":15.1051709}**}

{"nome":"Alì","codice":"083002","regione":"sicilia","provincia":"messina","sigla":"ME","codiceCatastale":"A194","cap":"98020","coordinate"**:{"lat":"38.02694065","lng":"15.41797276"}**}

**Comment by Samurai016** [comment]
Ok a quanto pare c'era stato un errore quando ho inserito le coordinate, ho corretto
