### ISSUE TITLE
Wrong postal codes

### ISSUE THREAD

**Issue by sneps85** [Samurai016/Comuni-ITA-legacy#5]
Please overview the postal codes, as they seem to be not correct in some cases. E.g. Appiano sulla strada del vino return 39050 as postal code. This was once its postal code, but now the correct one would be 39057

**Comment by Samurai016** [comment]
Hi @sneps85, I fixed the problem and I improved the fetching system so that now it should more precise, but, because of the postal codes are got from Wikidata, sometimes they could be wrong (because in wikidata are stored the hamlet postal codes too).
Thank you for the reporting.
