### ISSUE TITLE
Request: Add phone number prefixes and istat numbers to the communities

### ISSUE THREAD

**Issue by sneps85** [Samurai016/Comuni-ITA-legacy#6]
Add phone number prefixes and istat numbers to the communities

**Comment by Samurai016** [comment]
Hi @sneps85, I added prefixes as suggested.
Now you can find the prefixes under the property `prefisso`.
The ISTAT numbers were yet present under the property `codice` (as you can see in the [docs](https://comuni-ita.herokuapp.com/#operation/comuni)).
Thanks for your suggestion.
