### ISSUE TITLE
Prendere tutti i comuni di una regione

### ISSUE THREAD

**Issue by Matt0550** [Samurai016/Comuni-ITA-legacy#7]
Salve, con la nuova versione come è possibile richiedere tutti i comuni di una determinata regione?
Usavo questo url `https://comuni-ita.herokuapp.com/api/comuni/sicilia?onlyname=true`
Ma mi da Regione inesistente

**Comment by Samurai016** [comment]
Salve @Matt0550, 
Ho aggiornato l'API (versione [2.8.2](https://github.com/Samurai016/Comuni-ITA/tree/2.8.2)) e ho fixato il problema. 
Grazie mille per la segnalazione.

**Comment by Matt0550** [comment]
Di nulla!
