### ISSUE TITLE
Possibilità di cercare un comune tramite key

### ISSUE THREAD

**Issue by bytemore** [Samurai016/Comuni-ITA-legacy#9]
Non so se sia già possibile ma sarebbe comodo poter ottenere un singolo comune tramite query come ad esempio
`https://comuni-ita.herokuapp.com/api/comuni?nome=milano`

Con risposta
```json
{
        "codice": "015146",
        "nome": "Milano",
        "nomeStraniero": null,
        "codiceCatastale": "F205",
        "cap": "20141",
        "prefisso": "02",
        "provincia": "015",
        "coordinate": {
            "lat": 45.46694564819336,
            "lng": 9.1899995803833
        }
},
```

**Comment by Samurai016** [comment]
Ciao @gianmazzoran,  
grazie per il suggerimento, ho modificato l'API (versione [2.9.0](../tree/2.9.0)) per supportare vari filtraggi, sia per nome del comune, che per codice, codice Catastale e/o CAP.
Stessa cosa per le province (nome, codice, sigla).
Trovi tutti gli aggiornamenti nella [documentazione](https://comuni-ita.herokuapp.com/#tag/comuni).
Ho sfruttato i query params come suggerito da te.
I filtri sono cumulabili (si possono concatenare) per ottenere vari risultati (ad esempio inserendo sia il filtro nome che il filtro CAP).

Grazie ancora!
